//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTestingDemo.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Content/Base Page template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    public partial class BasePage : global::Synthesis.StandardTemplateItem, global::MvcTestingDemo.Models.IBasePageItem {
        
        private Synthesis.FieldTypes.TextField _pageName;
        
        private Synthesis.FieldTypes.RichTextField _body;
        
        private Synthesis.FieldTypes.TextField _navigationName;
        
        private Synthesis.FieldTypes.BooleanField _includedInNavigation;
        
        public BasePage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public BasePage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Base Page";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{51B3971D-3D81-46F3-9713-D979F1BA28E8}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Page Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("page_name")]
        public Synthesis.FieldTypes.Interfaces.ITextField PageName {
            get {
                if (_pageName == null) {
                    _pageName = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E9BFDE69-9FE1-4A3D-A1E6-CD5402ABE237}"], "/sitecore/templates/Content/Base Page", "Page Name"), this.GetSearchFieldValue("page_name"));
                }
                return _pageName;
            }
        }
        
        /// <summary>Represents the Body field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("body")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField Body {
            get {
                if (_body == null) {
                    _body = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E7BAAD19-74D3-4023-BC74-185F5653C78F}"], "/sitecore/templates/Content/Base Page", "Body"), this.GetSearchFieldValue("body"));
                }
                return _body;
            }
        }
        
        /// <summary>Represents the Navigation Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_name")]
        public Synthesis.FieldTypes.Interfaces.ITextField NavigationName {
            get {
                if (_navigationName == null) {
                    _navigationName = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{0DEA15B4-8F41-4299-9154-50A55A17431D}"], "/sitecore/templates/Content/Base Page", "Navigation Name"), this.GetSearchFieldValue("navigation_name"));
                }
                return _navigationName;
            }
        }
        
        /// <summary>Represents the IncludedInNavigation field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("includedinnavigation")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField IncludedInNavigation {
            get {
                if (_includedInNavigation == null) {
                    _includedInNavigation = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{B040A186-B8DA-4100-98B4-660186DEEC75}"], "/sitecore/templates/Content/Base Page", "IncludedInNavigation"), this.GetSearchFieldValue("includedinnavigation"));
                }
                return _includedInNavigation;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    public class BasePageInitializer : Synthesis.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{51B3971D-3D81-46F3-9713-D979F1BA28E8}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new BasePage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new BasePage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Content/Blurb template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    public partial class Blurb : global::Synthesis.StandardTemplateItem, global::MvcTestingDemo.Models.IBlurbItem {
        
        private Synthesis.FieldTypes.TextField _headline;
        
        private Synthesis.FieldTypes.RichTextField _blurbBody;
        
        private Synthesis.FieldTypes.HyperlinkField _link;
        
        public Blurb(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Blurb(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Blurb";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{C3C73991-7AEA-42BA-8AFC-624FDA137EDE}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Headline field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("headline")]
        public Synthesis.FieldTypes.Interfaces.ITextField Headline {
            get {
                if (_headline == null) {
                    _headline = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{0DAC2125-BD2D-4D22-BE2F-9BB08A193299}"], "/sitecore/templates/Content/Blurb", "Headline"), this.GetSearchFieldValue("headline"));
                }
                return _headline;
            }
        }
        
        /// <summary>Represents the Blurb Body field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("blurb_body")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField BlurbBody {
            get {
                if (_blurbBody == null) {
                    _blurbBody = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{02ABD6E2-A8E2-4A6D-A4C0-79EEF024E073}"], "/sitecore/templates/Content/Blurb", "Blurb Body"), this.GetSearchFieldValue("blurb_body"));
                }
                return _blurbBody;
            }
        }
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get {
                if (_link == null) {
                    _link = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{58344C8B-F2D8-4BAB-9C70-24050F5023E1}"], "/sitecore/templates/Content/Blurb", "Link"), this.GetSearchFieldValue("link"));
                }
                return _link;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    public class BlurbInitializer : Synthesis.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{C3C73991-7AEA-42BA-8AFC-624FDA137EDE}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Blurb(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Blurb(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Content/Navigable template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    public partial class Navigable : global::Synthesis.StandardTemplateItem, global::MvcTestingDemo.Models.INavigableItem {
        
        private Synthesis.FieldTypes.TextField _navigationName;
        
        private Synthesis.FieldTypes.BooleanField _includedInNavigation;
        
        public Navigable(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Navigable(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Navigable";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{342FE524-2454-477B-BA28-2AB854F62F99}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Navigation Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_name")]
        public Synthesis.FieldTypes.Interfaces.ITextField NavigationName {
            get {
                if (_navigationName == null) {
                    _navigationName = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{0DEA15B4-8F41-4299-9154-50A55A17431D}"], "/sitecore/templates/Content/Navigable", "Navigation Name"), this.GetSearchFieldValue("navigation_name"));
                }
                return _navigationName;
            }
        }
        
        /// <summary>Represents the IncludedInNavigation field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("includedinnavigation")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField IncludedInNavigation {
            get {
                if (_includedInNavigation == null) {
                    _includedInNavigation = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{B040A186-B8DA-4100-98B4-660186DEEC75}"], "/sitecore/templates/Content/Navigable", "IncludedInNavigation"), this.GetSearchFieldValue("includedinnavigation"));
                }
                return _includedInNavigation;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    public class NavigableInitializer : Synthesis.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{342FE524-2454-477B-BA28-2AB854F62F99}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Navigable(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Navigable(searchFields);
        }
    }
}
