//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTestingDemo.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Content/Base Page template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{51B3971D-3D81-46F3-9713-D979F1BA28E8}", "jgBwq2K3IQGfFPyuHYuizR916JY=")]
    public partial interface IBasePageItem : global::MvcTestingDemo.Models.INavigableItem {
        
        /// <summary>Represents the Page Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("page_name")]
        Synthesis.FieldTypes.Interfaces.ITextField PageName {
            get;
        }
        
        /// <summary>Represents the Body field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("body")]
        Synthesis.FieldTypes.Interfaces.IRichTextField Body {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Content/Blurb template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{C3C73991-7AEA-42BA-8AFC-624FDA137EDE}", "Q+aX0nRQPXQ81gWHX+rRsW6LVVY=")]
    public partial interface IBlurbItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Headline field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("headline")]
        Synthesis.FieldTypes.Interfaces.ITextField Headline {
            get;
        }
        
        /// <summary>Represents the Blurb Body field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("blurb_body")]
        Synthesis.FieldTypes.Interfaces.IRichTextField BlurbBody {
            get;
        }
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Content/Navigable template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "7.2.0.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{342FE524-2454-477B-BA28-2AB854F62F99}", "Qp02DUyeqsFzWQMa2CsyALF6Jg0=")]
    public partial interface INavigableItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Navigation Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_name")]
        Synthesis.FieldTypes.Interfaces.ITextField NavigationName {
            get;
        }
        
        /// <summary>Represents the IncludedInNavigation field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("includedinnavigation")]
        Synthesis.FieldTypes.Interfaces.IBooleanField IncludedInNavigation {
            get;
        }
    }
}
